### ISSUE TITLE
please backport/release the id fix from 3.4-dev to 3.3 stable

### ISSUE THREAD

**Issue by c33s** [craue/CraueFormFlowDemoBundle#9]
currently this bundle breaks with symfony maker in the stable 3.3 version but the missing ids are already there in 3.4-dev. please also release them for 3.3.
```
php bin/console make:entity

In MappingException.php line 52:

  No identifier/primary key specified for Entity "Craue\FormFlowDemoBundle\Entity\Driver". Every Entity must have an identifier/primary key.
```

**Comment by craue** [comment]
I won't backport this commit but plan to release 3.4 soon.
